services:
  common:
    build:
      context: common/.
    ports:
      - 127.0.0.1:8080:80
    environment:
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_ACCESS_KEY=${DO_SPACES_ACCESS_KEY}
      - DO_SPACES_SECRET_KEY=${DO_SPACES_SECRET_KEY}
      - FLOW_DB_USER=${FLOW_DB_USER}
      - FLOW_DB_PASSWORD=${FLOW_DB_PASSWORD}
      - FLOW_DB_NAME=${FLOW_DB_NAME}
      - FLOW_DB_PORT=${FLOW_DB_PORT}
      - FLOW_DB_HOST=${FLOW_DB_HOST}
    volumes:
      - ./common/:/home/site/wwwroot/
      - ./artifacts/:/home/artifacts/
    links:
      - postgis:$FLOW_DB_HOST
  postgis:
    build:
      context: postgis/.
    environment:
      - POSTGRES_USER=${FLOW_DB_USER}
      - POSTGRES_PASSWORD=${FLOW_DB_PASSWORD}
      - POSTGRES_DB=${FLOW_DB_NAME}
    ports:
      - 8001:5432
